# Generated by Django 6.0.3 on 2026-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_chat_message"),
    ]

    def _normalize_blank_emails(apps, schema_editor):
        User = apps.get_model("users", "User")
        seen = set()
        qs = (
            User.objects.all()
            .only("id", "username", "email")
            .order_by("id")
        )
        for u in qs.iterator():
            raw = u.email or ""
            email = raw.strip()
            if not email:
                base = (u.username or "user").strip() or "user"
                u.email = f"{base}_{u.id}@example.invalid"
                u.save(update_fields=["email"])
                seen.add(u.email.lower())
                continue

            key = email.lower()
            if key in seen:
                if "@" in email:
                    local, domain = email.split("@", 1)
                    u.email = f"{local}+dup{u.id}@{domain}"
                else:
                    base = (u.username or "user").strip() or "user"
                    u.email = f"{base}_{u.id}@example.invalid"
                u.save(update_fields=["email"])
                seen.add(u.email.lower())
                continue

            if email != raw:
                u.email = email
                u.save(update_fields=["email"])
            seen.add(key)

    operations = [
        migrations.RunPython(_normalize_blank_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
