# Generated by Django 5.2.9 on 2026-02-18 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookShelfItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_books_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=300)),
                ("authors", models.CharField(blank=True, max_length=500)),
                ("thumbnail", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WANT_TO_READ", "Want to read"),
                            ("IN_PROGRESS", "In progress"),
                            ("FINISHED", "Finished"),
                        ],
                        default="WANT_TO_READ",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_shelf_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "google_books_id")},
            },
        ),
    ]
