# Generated by Django 5.2.9 on 2026-03-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_poll_post_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubpoll",
            name="option1_media_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="clubpoll",
            name="option1_media_type",
            field=models.CharField(
                blank=True,
                choices=[("BOOK", "Book"), ("MOVIE", "Movie"), ("PODCAST", "Podcast")],
                default="BOOK",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="clubpoll",
            name="option2_media_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="clubpoll",
            name="option2_media_type",
            field=models.CharField(
                blank=True,
                choices=[("BOOK", "Book"), ("MOVIE", "Movie"), ("PODCAST", "Podcast")],
                default="BOOK",
                max_length=10,
            ),
        ),
    ]
