# Generated by Django 5.2.9 on 2026-03-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_poll_name_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubpost",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
