# Generated by Django 5.2.9 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_club_post_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookshelfitem",
            name="isbn",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="bookshelfitem",
            name="review",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="movieshelfitem",
            name="review",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="podcastshelfitem",
            name="review",
            field=models.TextField(blank=True),
        ),
    ]
