# Generated by Django 5.2.9 on 2026-03-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0006_add_review_and_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookshelfitem",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="movieshelfitem",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="podcastshelfitem",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
